//
//  MoviesInteractor.swift
//  MoviesAppVIP
//
//  Created by Kamil Zajac on 17.06.2017.
//  Copyright (c) 2017 Kamil Zajac. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MoviesInteractorInput
{
    func startDownloadMovies(request: Movies.Download.Request)
}

protocol MoviesInteractorOutput
{
    func returnJsonToConvert(response: Movies.Download.Response.Json)
    func returnErrorFromWorker(response: Movies.Download.Response.Error)
}

class MoviesInteractor: MoviesInteractorInput
{
    var output: MoviesInteractorOutput!
    var worker: MoviesWorker!
    
    // MARK: - Business logic
    
    func startDownloadMovies(request: Movies.Download.Request)
    {
        
        // NOTE: Create some Worker to do the work
        
        worker = MoviesWorker()
        worker.downloadMoviesWith(movieType: request.movieType, and: request.page) { [weak self] (result) in
            switch result {
            case .Success(let moviesDict):
                let response = Movies.Download.Response.Json(moviesDict: moviesDict)
                self?.output.returnJsonToConvert(response: response)
            case .Error(let error):
                let response = Movies.Download.Response.Error(error: error)
                self?.output.returnErrorFromWorker(response: response)
            }
        }
        
        
    }
}
