//
//  MoviesConfigurator.swift
//  MoviesAppVIP
//
//  Created by Kamil Zajac on 17.06.2017.
//  Copyright (c) 2017 Kamil Zajac. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension MoviesViewController: MoviesPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension MoviesInteractor: MoviesViewControllerOutput
{
}

extension MoviesPresenter: MoviesInteractorOutput
{
}

class MoviesConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = MoviesConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: MoviesViewController)
  {
    let router = MoviesRouter()
    router.viewController = viewController
    
    let presenter = MoviesPresenter()
    presenter.output = viewController
    
    let interactor = MoviesInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
